### PR TITLE
Migrate utils to top-level functions for true static methods.

### PR DESCRIPTION
**Pull request by JakeWharton**
@JvmStatic methods in an 'object' actually generate two methods: instance ones with the actual method body and static ones which proxy to the instance ones through a singleton instance. Top-level functions are truly static in the bytecode allowing faster dispatch and halves the method count requirement of the class.

### CODE REVIEW

**Comment by ansman** [comment]
I'm worried about clobbering the global namespace. For the most part it's not too bad but still.

**Comment by JakeWharton** [comment]
Ah, yeah. I hadn't thought about that.

**Comment by ansman** [comment]
I'm not saying it isn't worth it. We would just have to make sure we're not leaking anything too bad.

**Comment by JakeWharton** [comment]
It could be written in Java... The horror!

**Comment by ansman** [comment]
What if we use the field for accessing the object? You’d still get the worse performant call and a field but no additional methods.

**Comment by ansman** [comment]
@JakeWharton So what are your thoughts?

**Comment by JakeWharton** [comment]
I don't have a strong opinion. If it were my project I'd probably write
them in Java. I'm happy with them being referenced as member functions by
the instance though.

**Comment by LouisCAD** [comment]
Wouldn't `internal` visibility allow top-level functions without polluting the global namespace?

**Comment by JakeWharton** [comment]
No. It has to be accessible to the generated code which is in a different
compilation unit.

**Comment by ansman** [comment]
`internal` can't be used since the Kotshi API is a separate compilation unit from the generated code.

**Comment by ansman** [comment]
Actually Kotlin doesn't generate proxy methods for `object` when using `@JvmStatic`. It's only for companion objects.

**Pull request closed without merging**
