### PR TITLE
Allow the pre 1.0 way of implementing the factory

### LINKED ISSUE #58: Factory not generated sometimes
When running my app which uses kotshi in a module from android studio, everything is fine.
However when I run it from commandline in tests, it fails because the adapter factory is not generated.

I made a sample probject:
https://github.com/PaulWoitaschek/KotshiFactoryBug

which fails when running `./gradlew test`

### PR DESCRIPTION
**Pull request by ansman**
Hopefully fixes #58

### CODE REVIEW

**Comment by JakeWharton** [comment]
Test case?

**Comment by ansman** [comment]
I just tested it manually, I need a separate module to have multiple factories and for some reason it did not work having a factory in the test module's test sourceset.

**Comment by JakeWharton** [comment]
Ah, right. Did you add `testAnnotationProcessor project(':kotshi-compiler')`?

**Comment by ansman** [comment]
I tried adding `kaptTest project(':compiler')`. Strangely it compiles just fine but nothing seems to generated and there are still errors in the file.

**Pull request merged**
