### PR TITLE
Use JsonAdapter.nullSafe.

### PR DESCRIPTION
**Pull request by NightlyNexus**
This isn't a behavior change, but it helps with toString debugging.

### CODE REVIEW

**Comment by ansman** [comment]
What becomes easier with toString? This would of course create one extra object per adapter so unless there is a good reason I feel like the overhead isn't worth it.

**Comment by NightlyNexus** [comment]
The toString of `nullSafe` indicates that it's null-safe.
Also, all internal JsonAdapter implementations in Moshi use nullSafe instead of checking themselves. I don't mind overhead within factory methods.
That said, I'm happy to close, if you'd prefer.

**Comment by ansman** [comment]
Oh I see, well yeah. I guess the overhead isn't too bad since they are just empty objects. 
What should a good `toString` method do?

The alternative would be as you suggest in #50 to implement `toString` on each adapter but that would add one extra method per adapter which I would assume @JakeWharton is against.

**Comment by ansman** [comment]
Closing this in favor for #52

**Pull request closed without merging**
