### PR TITLE
Fix an issue with generics being used as generic type arguments

### LINKED ISSUE #41: Generic type leads to invalid generated code
Here's an example of type parameterized model:
```kotlin
@JsonSerializable
data class PagedResult<out Data>(val data: List<Data>, val meta: MetaData) {
    @JsonSerializable
    data class MetaData(val total: Int,
                        val count: Int,
                        @Json(name = "per_page")
                        val resultsPerPage: Int,
                        @Json(name = "current_page")
                        val currentPage: Int,
                        @Json(name = "total_pages")
                        val totalPages: Int)
}
```
The generated code attempts to refer to `Data.class` which is incorrect since it's a type parameter.

### PR DESCRIPTION
**Pull request by ansman**
This fixes #41

### CODE REVIEW

**Comment by LouisCAD** [comment]
@ansman I'd add a few more complex and one more simple tests before releasing, including a type parameterized property (not in a List or other generic structure), to be sure it works in all cases

**Comment by ansman** [comment]
@LouisCAD Awesome, thanks!

**Comment by LouisCAD** [comment]
@ansman I can't add commits to this PR, but here's more simple, and complex models that can be tested:
```kotlin
@JsonSerializable
data class ParameterizedModel<out Data>(val data: Data)

@JsonSerializable
data class TripleParameterizedModel<out Data, out T : CharSequence, out E : Any>(val e: E, val data: Data, val t: T)

@JsonSerializable
data class TypeCeption<out D>(
        val tpm: TripleParameterizedModel<ParameterizedModel<IntArray>, String, D>,
        val pm: ParameterizedModel<List<D>>
)
```

I hope you will never have to write something like this for an actual "REST" API though 😂 🤣

**Comment by ansman** [comment]
There are the constructors in order:
```kotlin
  public KotshiParameterizedModelJsonAdapter(Moshi moshi, Type[] types) {
    adapter0 = moshi.adapter(types[0]);
  }

  public KotshiTripleParameterizedModelJsonAdapter(Moshi moshi, Type[] types) {
    adapter0 = moshi.adapter(types[2]);
    adapter1 = moshi.adapter(types[0]);
    adapter2 = moshi.adapter(types[1]);
  }

  public KotshiTypeCeptionJsonAdapter(Moshi moshi, Type[] types) {
    adapter0 = moshi.adapter(Types.newParameterizedType(TripleParameterizedModel.class, Types.newParameterizedType(ParameterizedModel.class, int[].class), String.class, types[0]));
    adapter1 = moshi.adapter(Types.newParameterizedType(ParameterizedModel.class, Types.newParameterizedType(List.class, types[0])));
  }
```

So it seems to work fine.

**Comment by LouisCAD** [comment]
Looks good!
Will check that on January, 2nd when I'm back from vacation

**Pull request merged**
